spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sypastebin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123