spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sypastebin?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #druid 数据源配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,logback
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  data:
    mongodb:
      database: sypastebin
      host: 127.0.0.1
      port: 27017
      username: user
      password: admin123

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: top.zy68.Model

logging:
  config: classpath:logback-spring.xml

server:
  tomcat:
    max-http-form-post-size: -1 # 取消最大post上传限制
